version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - POSTGRES_DB=flaskdb
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: